# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BrotherPrinter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BrotherPrinter
  pod 'BRPtouchPrinterKit', :git => 'https://github.com/envoy/BRPtouchPrinterKit.git'
end
